spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/mydb
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 9090

microservices:
  coupon:
    url: http://udemy-coupon-service:9091/coupon-api/coupons/