apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-mysql
  template:
    metadata:
      name: docker-mysql
      labels:
        app: docker-mysql
    spec:
      volumes:
        - name: mysql-initdb-vol
          configMap:
            name: mysql-initdb-config
      containers:
        - name: docker-mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-initdb-vol
          env:
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_ROOT_PASSWORD
              value: test1234
            - name: MYSQL_ROOT_HOST
              value: '%'
      restartPolicy: Always
