apiVersion: v1
kind: Service
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  selector:
    app: docker-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30287
  type: NodePort