apiVersion: v1
kind: Service
metadata:
  name: udemy-product-service
  labels:
    app: udemy-product-service
spec:
  selector:
    app: udemy-product-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30289
  type: NodePort